name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: idokad/ido-image
          tags: newtag

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push files to another repository
  # You may pin to the exact commit or the version.
  # uses: timthedev07/copy_file_to_another_repo_action@6216f0ab1805b8eb761d7921db70ffbe201928db
        uses: timthedev07/copy_file_to_another_repo_action@v1.33.0
        with:
    # Source file from the origin directory
            source_file: checkout.md
    # Destination repository
            destination_repo: idokadosh5/helloworld.git
    # Directory to push the file to
            destination_folder: # optional
    # Email for the git commit
            user_email: idokad@gmail.com
    # GitHub username for the commit
            user_name: idokadosh5
    # branch to push file to, defaults to master
            destination_branch: # optional
    # Destination branch to create for this commit
            destination_branch_create: # optional
    # A custom message for the commmit
            commit_message: # optional
          
